/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddRoleForm: typeof import('./src/components/home/system/AddRoleForm.vue')['default']
    AddUserForm: typeof import('./src/components/home/system/AddUserForm.vue')['default']
    DSearch: typeof import('vue-devui/search/index.es.js')['Search']
    DTree: typeof import('vue-devui/tree/index.es.js')['Tree']
    EditBaseInfoForm: typeof import('./src/components/home/base/EditBaseInfoForm.vue')['default']
    EditUserInfoForm: typeof import('./src/components/home/system/EditUserInfoForm.vue')['default']
    EditUserRoleForm: typeof import('./src/components/home/system/EditUserRoleForm.vue')['default']
    ExcelTable: typeof import('./src/components/home/ExcelTable.vue')['default']
    ForgetPasswordForm: typeof import('./src/components/login/ForgetPasswordForm.vue')['default']
    ForgetWindows: typeof import('./src/components/ForgetWindows.vue')['default']
    GradeSelect: typeof import('./src/components/home/GradeSelect.vue')['default']
    MajorSelect: typeof import('./src/components/home/MajorSelect.vue')['default']
    RouterBreadcrumb: typeof import('./src/components/home/RouterBreadcrumb.vue')['default']
    RouterContainer: typeof import('./src/components/basic/RouterContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterSideMenu: typeof import('./src/components/home/RouterSideMenu.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    SelectPermission: typeof import('./src/components/home/system/SelectPermission.vue')['default']
  }
}
