/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddRoleForm: typeof import('./src/components/home/system/AddRoleForm.vue')['default']
    AddUserForm: typeof import('./src/components/home/system/AddUserForm.vue')['default']
    DSearch: typeof import('vue-devui/search/index.es.js')['Search']
    DTree: typeof import('vue-devui/tree/index.es.js')['Tree']
    EditRoleForm: typeof import('./src/components/home/system/EditRoleForm.vue')['default']
    EditUserInfoForm: typeof import('./src/components/home/system/EditUserInfoForm.vue')['default']
    EditUserRoleForm: typeof import('./src/components/home/system/EditUserRoleForm.vue')['default']
    RouterBreadcrumb: typeof import('./src/components/home/RouterBreadcrumb.vue')['default']
    RouterContainer: typeof import('./src/components/basic/RouterContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterSideMenu: typeof import('./src/components/home/RouterSideMenu.vue')['default']
    RouterSiderMenu: typeof import('./src/components/home/RouterSiderMenu.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    SelectPermission: typeof import('./src/components/home/system/SelectPermission.vue')['default']
  }
}
