import { reactive } from 'vue'
import { defineStore } from 'pinia'
import type { EnrollmentItem } from '@/model'

export const useEnrollmentStore = defineStore('enrollment', () => {
    let enrollment = reactive<EnrollmentItem>({
        enrollmentId: '',
        studentId: '',
        idNumber: '',
        name: '',
        gender: '',
        birthdate: '',
        hobbies: '',
        nativePlace: '',
        nation: '',
        height: '',
        weight: '',
        politicId: '',
        politicStatus: '',
        phone: '',
        email: '',
        headerTeacherUsername: '',
        headerTeacherRealName: '',
        headerTeacherPhone: '',
        dormitory: '',
        classNo: '',
        majorId: '',
        majorName: '',
        degreeId: '',
        degreeName: '',
        gradeId: '',
        gradeName: '',
        studentType: '',
        admissionBatch: '',
        subjectCategory: '',
        provinceName: '',
        examId: '',
        admittedMajor: '',
        volunteerMajor: '',
        volunteerCollege: '',
        totalExamScore: '',
        convertedScore: '',
        specialScore: '',
        feature: '',
        volunteer1: '',
        volunteer2: '',
        volunteer3: '',
        volunteer4: '',
        volunteer5: '',
        volunteer6: '',
        studentFrom: '',
        isAdjusted: false,
        receiver: '',
        receiverPhone: '',
        postalCode: '',
        householdRegistration: '',
        householdType: '',
        address: '',
        fatherName: '',
        fatherPhone: '',
        fatherOccupation: '',
        motherName: '',
        motherPhone: '',
        motherOccupation: '',
        guardian: '',
        guardianPhone: '',
        familyPopulation: '',
        familyMembers: '',
        familyLocation: '',
        isOnlyChild: false,
        highSchoolCode: '',
        highSchoolName: '',
        candidateCategoryClassification: '',
        graduationCategoryClassification: '',
        graduationCategory: '',
        candidateCategory: '',
        foreignLanguage: '',
        scoreChinese: '',
        scoreMath: '',
        scoreForeignLanguage: '',
        scoreComprehensive: '',
        scorePhysics: '',
        scoreChemistry: '',
        scoreBiology: '',
        scorePolitics: '',
        scoreHistory: '',
        scoreGeography: '',
        scoreTechnology: '',
        selectedSubjects: '',
        studentLoans: false,
        disability: false,
        religiousBeliefs: '',
        otherNotes: '',
        enabled: false
    })
    const getInfo = () => {
        return enrollment
    }
    const setInfo = (newEnrollment: EnrollmentItem) => {
        enrollment = newEnrollment
    }
    return { getInfo, setInfo }
})